<?php
/** Rodapé, botão do WhatsApp e script. Espera: $asset e $home. */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?><footer class="site-footer"><div class="shell footer-grid">
	<div class="footer-brand"><img src="<?php echo $asset( 'assets/images/footer-logo.avif' ); ?>" alt="Instituto Raphael Veiga"><div class="social"><a href="https://www.instagram.com/institutoraphaelveiga" target="_blank" rel="noopener noreferrer" aria-label="Instagram"><img src="<?php echo $asset( 'assets/images/instagram.png' ); ?>" alt=""></a><a href="https://www.facebook.com/instituto.raphaelveiga" target="_blank" rel="noopener noreferrer" aria-label="Facebook"><img src="<?php echo $asset( 'assets/images/facebook-app-round-white-icon.webp' ); ?>" alt=""></a><a href="https://www.linkedin.com/company/instituto-raphael-veiga/" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn"><img src="<?php echo $asset( 'assets/wix/11062b_7dcffe5daf2944b7be0a46ac6d472634~mv2.png' ); ?>" alt=""></a></div></div>
	<div><h2>Navegação</h2><a href="<?php echo esc_url( $home ); ?>">Início</a><a href="<?php echo esc_url( home_url( '/quem-somos/' ) ); ?>">Quem somos</a><a href="<?php echo esc_url( home_url( '/o-que-fazemos/' ) ); ?>">O que fazemos</a><a href="<?php echo esc_url( home_url( '/noticias/' ) ); ?>">Notícias</a><a href="<?php echo esc_url( home_url( '/faca-parte/' ) ); ?>">Faça parte</a></div>
	<div><h2>Transparência</h2><a href="https://fd050c3b-58d1-4440-8228-a7a886a60b02.filesusr.com/ugd/e09d66_f3fcf788dcee4b7e95cda50f5fe553d8.pdf">Relatórios de Atividades</a><a href="https://fd050c3b-58d1-4440-8228-a7a886a60b02.filesusr.com/ugd/e09d66_fccd29c9f2b0467f958a45c06b9fca54.pdf">Prestação de contas</a><a href="<?php echo esc_url( home_url( '/politica-de-privacidade/' ) ); ?>">Política de privacidade</a><p class="footer-cnpj">CNPJ: 47.732.142/0001-07</p></div>
	<div><h2>Contato</h2><a href="https://wa.me/551120123307" target="_blank" rel="noopener noreferrer">(11) 2012-3307</a><a href="mailto:atendimento@institutoraphaelveiga.org.br">atendimento@institutoraphaelveiga.org.br</a><p>Rua Dr. Paulo Queiroz, 1244<br>Jardim Nove de Julho<br>São Paulo/SP</p></div>
</div><div class="footer-bottom"><div class="shell"><div class="footer-signature"><span class="footer-copy">© Instituto Raphael Veiga</span><span class="footer-dot" aria-hidden="true"> · </span><span class="footer-credit">UM PROJETO <a href="https://www.tomatoconsultoria.com/" target="_blank" rel="noopener noreferrer">TOMATO</a> + <a href="https://www.uttopya.com.br/" target="_blank" rel="noopener noreferrer">UTTOPYA</a></span></div></div></div></footer>
<a class="whatsapp-float" href="https://wa.me/551120123307" target="_blank" rel="noopener noreferrer" aria-label="Falar com o Instituto Raphael Veiga pelo WhatsApp"><svg aria-hidden="true" viewBox="0 0 32 32"><path d="M16 4A12 12 0 0 0 5.7 22.2L4 28l5.9-1.6A12 12 0 1 0 16 4Z"/><path class="whatsapp-phone" d="M11.1 9.5c-.4 0-.7.2-1 .6-1.2 1.4-.9 3.6.7 6.2 1.8 3 4.6 5.3 7.8 6.4 2.5.8 4.5.2 5.2-.9.4-.7.5-1.5.3-1.7l-3.7-1.8c-.3-.1-.5-.1-.7.2l-1.1 1.4c-.2.3-.5.3-.9.1-1.6-.7-3-1.7-4.1-3.1-.3-.4-.3-.7 0-1l1-1.2c.2-.3.3-.6.1-1l-1.7-3.8c-.2-.4-.5-.5-.9-.5Z"/></svg></a>
<script src="<?php echo $asset( 'assets/js/irv.js?v=' . IRV_SITE_VERSION ); ?>" defer></script>
